# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "ghcr.io/herbvertuher/5_tgbot_go"
  tag: "v1.0.14-213676e"
  arch: "amd64"
secret:
  name: "kbot"
  tokenName: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
