# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "herbvertuher/5_tgbot_go"
  tag: "v1.0.17-e1af920"
  os: "linux"
  arch: "amd64"
secret:
  name: "kbot"
  tokenName: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
